on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.15'
      # exclude integration tests which have various external dependencies we don't support
      - run: go test $(go list ./... | grep -v integration-tests)
